#version: "3.8"
name: 'book-store-application'
services:
  catalog-db:
    image: postgres:16-alpine
    container_name: catalog_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES-DB=postgres
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      - bookstore-net

  orders-db:
    image: postgres:16-alpine
    container_name: orders_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES-DB=postgres
    ports:
      - "25432:5432"
    healthcheck:
      test: [ "CMD-SHELL","pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      - bookstore-net

  bookstore-rabbitmq:
    image: rabbitmq:4.0.4-management
    container_name: bookstore-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      - bookstore-net


  notifications-db:
    image: postgres:16-alpine
    container_name: notifications_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES-DB=postgres
    ports:
      - "35432:5432"
    healthcheck:
      test: [ "CMD-SHELL","pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      - bookstore-net

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - bookstore-net

#https://github.com/jinnabaalu/infinite-containers/blob/main/keycloak/dev-compose-standalone.yml
#--import-realm
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    container_name: keycloak
    command: ['start-dev','--import-realm']
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin1234
    volumes:
      - ./realm-config:/opt/keycloak/data/import
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - bookstore-net

networks:
  bookstore-net:
    driver: bridge